version: '3.6.4.{build}'
environment:
  access_token:
    secure: cBjCd4Q0pww6q7jKVN/LDBSHTMzmB+77vLQ9j4yq/KneIQi74rl6TgB4+5X7sd9w
skip_tags: true
image: Visual Studio 2017
clone_folder: c:\project\gallifrey
build_script:
- cmd: build.cmd
test: off
deploy: off
notifications:
- provider: GitHubPullRequest
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true