environment:
  github_api_key:
    secure: cBjCd4Q0pww6q7jKVN/LDBSHTMzmB+77vLQ9j4yq/KneIQi74rl6TgB4+5X7sd9w
  cloudflare_api_key:
    secure: pxNm/jQTuCJiffMNb4eBa7UVnzERRQQ4txXX45khVAuNBsgNxXnwMDQ67lC2zrrt
  cloudflare_zone:
    secure: qN/S16EFstjHdpD+CqmQPi5nB+PNQ6appSFSPg+WFYwXZJ+gxsdmZRLluO4nnsjn
  cloudflare_email:
    secure: 7MMGMp4bOy0b/HWDC5vBEbDm/S7GPCZCcy6zAPOjhVo=
  exceptionless_api_key:
    secure: owf/eHBH82XG+SWozC/GXMy+rD4zRHPlbjjFY0lH9ZKb2cKlWGPiXobT/uQKdDGd
skip_commits:
  files:
    - .fake/*
    - .github/*
    - .paket/*
    - docs/*
    - '**/*.html'
    - '**/*.md'
version: '3.22.5.{build}'
skip_tags: true
image: Visual Studio 2019
clone_folder: c:\project\gallifrey
build_script:
- cmd: build.cmd
test: off
deploy: off
notifications:
- provider: GitHubPullRequest
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
init:
- ps: new-itemproperty -path "HKLM:\SOFTWARE\Microsoft\.NETFramework\v4.0.30319" -name "SchUseStrongCrypto" -Value 1 -PropertyType "DWord";
- ps: new-itemproperty -path "HKLM:\SOFTWARE\Wow6432Node\Microsoft\.NETFramework\v4.0.30319" -name "SchUseStrongCrypto" -Value 1 -PropertyType "DWord"