namespace Gallifrey.AppTracking
{
    public enum TrackingType
    {
        AppLoad,
        ExportOccurred,
        UpdateCheck,
        UpdateCheckManual,
        AppClose,
        DailyHeartbeat,
        OptOut,
        TimerAdded,
        TimerDeleted,
        DonateClick,
        GitHubClick,
        ContactClick,
        LockedTimerAdd,
        SearchLoad,
        SearchFilter,
        SearchText,
        InformationShown,
        JiraConnectCloudRest,
        JiraConnectCloudRestWithTempo,
        JiraConnectSelfhostRest,
        JiraConnectSelfhostRestWithTempo,
        AutoUpdateInstalled,
        ManualUpdateRestart,
        ExportAll,
        ShowRunningTimer,
        MultipleInstancesRunning,
        SettingsMissing,
        NoInternet,
        ConnectionError,
        Heartbeat
    }
}
