#Basic Settings
title: Gallifrey App
description: "Get the best assistant to help manage your 'wibbily wobbly timey wimey' for Jira! A simple, light-weight Jira time logging companion to help you travel the Jira universe!"
url: https://www.gallifreyapp.co.uk
logo: /images/Logo.png
lang: en_GB
enableCsp: true

GoogleAnalytics: UA-51628201-1

#Webmaster tools
webmaster_verifications:
  google: mgN_dzKniNX81z2ReK46tTzOgoTND0YinWOLNZKMsws
  bing: 70C9C40BE160CF8A17564E2F00B21581

#Social
twitter:
    username: GallifreyApp
    card: summary

facebook:
   app_id: 1444417962337528
   publisher: 285001657
   admins: 285001657

social:
    name: Gallifrey App
    links:
        - https://www.twitter.com/GallifreyApp
        
#Link format
permalink: pretty

#Pagination
paginate: 5
paginate_path: "/news/page:num"

#Defaults
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      image: /images/Icon.png
      twitter_image_small: true
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      image: /images/Icon.png
      twitter_image_small: true

#Gems
gems:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
